const fakeData = [
    {
    "id": 1,
    "first_name": "Imogene",
    "last_name": "Brumpton",
    "email": "ibrumpton0@blogger.com",
    "gender": "Male",
    "phone": "936-675-0089",
    "salary": 11411,
    "country": "United States",
    "age": 26,
    "fav_movie": "Obvious Child",
    "image": "https://i.ibb.co/5cJ07VT/ratul.jpg"
  }, 
  {
    "id": 2,
    "first_name": "Jeffy",
    "last_name": "Jenman",
    "email": "jjenman1@mail.ru",
    "gender": "Male",
    "phone": "829-936-2033",
    "salary": 10823,
    "country": "China",
    "age": 45,
    "fav_movie": "Laggies",
    "image": "https://i.ibb.co/02pr21T/mehedi.jpg"
  }, 
  {
    "id": 3,
    "first_name": "Lucien",
    "last_name": "Bidmead",
    "email": "lbidmead2@github.com",
    "gender": "Male",
    "phone": "608-630-2348",
    "salary": 22202,
    "country": "Nigeria",
    "age": 27,
    "fav_movie": "George of the Jungle",
    "image": "https://i.ibb.co/b2KRLwT/arif.jpg"
  }, 
  {
    "id": 4,
    "first_name": "Ericha",
    "last_name": "Hanselman",
    "email": "ehanselman3@flavors.me",
    "gender": "Male",
    "phone": "838-532-6789",
    "salary": 17607,
    "country": "Philippines",
    "age": 28,
    "fav_movie": "Old Dogs",
    "image": "https://i.ibb.co/drw7214/sayed.jpg"
  }, 
  {
    "id": 5,
    "first_name": "Cheslie",
    "last_name": "Walles",
    "email": "cwalles4@wisc.edu",
    "gender": "Female",
    "phone": "444-408-5434",
    "salary": 24189,
    "country": "Russia",
    "age": 31,
    "fav_movie": "I Wish (Kiseki)",
    "image": "https://i.ibb.co/KKPVT3H/pranto.jpg"
  }, 
  {
    "id": 6,
    "first_name": "Marius",
    "last_name": "Habbijam",
    "email": "mhabbijam5@livejournal.com",
    "gender": "Female",
    "phone": "177-315-6372",
    "salary": 16743,
    "country": "Indonesia",
    "age": 33,
    "fav_movie": "Golden Age, The (Âge d'Or, L')",
    "image": "https://i.ibb.co/6WL3Rnx/asif.jpg"
  }, 
  {
    "id": 7,
    "first_name": "Wilt",
    "last_name": "Gaythorpe",
    "email": "wgaythorpe6@tuttocitta.it",
    "gender": "Male",
    "phone": "903-858-0058",
    "salary": 15493,
    "country": "Russia",
    "age": 49,
    "fav_movie": "Vidal Sassoon: The Movie",
    "image": "https://i.ibb.co/X8fn84p/shawon.jpg"
  }, 
  {
    "id": 8,
    "first_name": "Kerby",
    "last_name": "Egdal",
    "email": "kegdal7@blogger.com",
    "gender": "Female",
    "phone": "124-310-2248",
    "salary": 17590,
    "country": "China",
    "age": 47,
    "fav_movie": "Dracula A.D. 1972",
    "image" : "https://i.ibb.co/f4gg9Zm/shanto.jpg"
  }, 
  {
    "id": 9,
    "first_name": "Kira",
    "last_name": "Wigfall",
    "email": "kwigfall8@amazonaws.com",
    "gender": "Female",
    "phone": "423-720-2804",
    "salary": 17290,
    "country": "Bosnia and Herzegovina",
    "age": 40,
    "fav_movie": "Jönssonligan & den svarta diamanten",
    "image": "https://i.ibb.co/9Wk0LZq/shahed.jpg"
  }, 
  {
    "id": 10,
    "first_name": "Janice",
    "last_name": "Bilt",
    "email": "jbilt9@paypal.com",
    "gender": "Male",
    "phone": "590-691-2463",
    "salary": 20395,
    "country": "China",
    "age": 33,
    "fav_movie": "Hotel Reserve",
    "image": "https://i.ibb.co/qn6M7S0/sudip.jpg"
  }, 
  {
    "id": 11,
    "first_name": "Sherlocke",
    "last_name": "McQuorkel",
    "email": "smcquorkela@apple.com",
    "gender": "Male",
    "phone": "827-144-8591",
    "salary": 11134,
    "country": "Dominican Republic",
    "age": 30,
    "fav_movie": "Secret of the Grain, The (La graine et le mulet)",
    "image": "https://i.ibb.co/8bQGTNm/imran.jpg"
  }, 
  {
    "id": 12,
    "first_name": "Isadore",
    "last_name": "Grouen",
    "email": "igrouenb@japanpost.jp",
    "gender": "Male",
    "phone": "690-918-2156",
    "salary": 11803,
    "country": "Colombia",
    "age": 24,
    "fav_movie": "Rock-afire Explosion, The",
    "image" : "https://i.ibb.co/PTG5CS7/anik.jpg"
  }, 
  {
    "id": 13,
    "first_name": "Bordie",
    "last_name": "Cumberpatch",
    "email": "bcumberpatchc@fastcompany.com",
    "gender": "Female",
    "phone": "708-336-8608",
    "salary": 16067,
    "country": "Brazil",
    "age": 26,
    "fav_movie": "Safe Sex",
    "image": "https://i.ibb.co/kHTKYcQ/tuhin.jpg"
  }, 
  {
    "id": 14,
    "first_name": "Ulrica",
    "last_name": "Aslum",
    "email": "uaslumd@live.com",
    "gender": "Female",
    "phone": "200-337-0042",
    "salary": 15809,
    "country": "Panama",
    "age": 24,
    "fav_movie": "Road House",
    "image": "https://i.ibb.co/2Zh7mK7/drive-Safety.png"
  }, 
  {
    "id": 15,
    "first_name": "Glennis",
    "last_name": "Mardy",
    "email": "gmardye@icio.us",
    "gender": "Male",
    "phone": "726-688-6864",
    "salary": 19165,
    "country": "Chad",
    "age": 23,
    "fav_movie": "Soul Survivors (a.k.a. The Killer Cut)",
    "image": "https://i.ibb.co/yRNfxc8/ITHelp.png"
  }, 
  {
    "id": 16,
    "first_name": "Vinny",
    "last_name": "Escritt",
    "email": "vescrittf@woothemes.com",
    "gender": "Female",
    "phone": "948-584-6925",
    "salary": 17371,
    "country": "Brazil",
    "age": 23,
    "fav_movie": "Happiness of the Katakuris, The (Katakuri-ke no kôfuku)",
    "image": "https://i.ibb.co/58cxgzj/library-Books.png"
  }, 
  {
    "id": 17,
    "first_name": "Raynard",
    "last_name": "Melbourn",
    "email": "rmelbourng@archive.org",
    "gender": "Female",
    "phone": "394-317-3910",
    "salary": 11768,
    "country": "Indonesia",
    "age": 35,
    "fav_movie": "Thirteen Conversations About One Thing (a.k.a. 13 Conversations)",
    "image": "https://i.ibb.co/5r44bCk/school-Suffiles.png"
  }, 
  {
    "id": 18,
    "first_name": "Erskine",
    "last_name": "Wray",
    "email": "ewrayh@admin.ch",
    "gender": "Female",
    "phone": "922-199-8443",
    "salary": 22278,
    "country": "Indonesia",
    "age": 26,
    "fav_movie": "Good Bye (Bé omid é didar)",
    "image": "https://i.ibb.co/vkJQZCM/music-Lessons.png"
  }, 
  {
    "id": 19,
    "first_name": "Hernando",
    "last_name": "Boyack",
    "email": "hboyacki@archive.org",
    "gender": "Male",
    "phone": "879-959-9388",
    "salary": 29001,
    "country": "Russia",
    "age": 22,
    "fav_movie": "Something Is Happening (Kuch Kuch Hota Hai)",
    "image" : "https://i.ibb.co/3fYh4FQ/Rectangle-27.png"
  }, 
  {
    "id": 20,
    "first_name": "Helenelizabeth",
    "last_name": "Callcott",
    "email": "hcallcottj@google.fr",
    "gender": "Female",
    "phone": "504-961-0793",
    "salary": 18850,
    "country": "China",
    "age": 47,
    "fav_movie": "Post Grad",
    "image": "https://i.ibb.co/jbnTV3F/good-Education.png"
  }
];

  export default fakeData;
